"""Add deploy stage fields to issue resolution

Revision ID: 1beed1f47ecb
Revises: 2c4f7fce0e15
Create Date: 2025-11-19 22:47:08.590130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1beed1f47ecb'
down_revision = '2c4f7fce0e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployment_hooks', 'phase',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('issue_resolutions', sa.Column('deploy_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Add deploy_complete as nullable first
    op.add_column('issue_resolutions', sa.Column('deploy_complete', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE issue_resolutions SET deploy_complete = FALSE WHERE deploy_complete IS NULL")
    # Now make it NOT NULL
    op.alter_column('issue_resolutions', 'deploy_complete', nullable=False)

    op.add_column('issue_resolutions', sa.Column('deploy_started_at', sa.DateTime(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('deploy_completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_issue_resolutions_deploy_session_id'), 'issue_resolutions', ['deploy_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_resolutions_deploy_session_id'), table_name='issue_resolutions')
    op.drop_column('issue_resolutions', 'deploy_completed_at')
    op.drop_column('issue_resolutions', 'deploy_started_at')
    op.drop_column('issue_resolutions', 'deploy_complete')
    op.drop_column('issue_resolutions', 'deploy_session_id')
    op.alter_column('deployment_hooks', 'phase',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###