"""add_credit_expiration_and_premium_tier

Revision ID: 30c8c00d45e0
Revises: d9f4a6c7e8b9
Create Date: 2025-11-21 14:26:53.977118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30c8c00d45e0'
down_revision = 'd9f4a6c7e8b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin_transactions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('coin_transactions', sa.Column('expired', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('coin_transactions', sa.Column('expired_at', sa.DateTime(), nullable=True))
    op.add_column('coin_transactions', sa.Column('package_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_coin_transactions_expired'), 'coin_transactions', ['expired'], unique=False)
    op.create_index(op.f('ix_coin_transactions_expires_at'), 'coin_transactions', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_transactions_expires_at'), table_name='coin_transactions')
    op.drop_index(op.f('ix_coin_transactions_expired'), table_name='coin_transactions')
    op.drop_column('coin_transactions', 'package_id')
    op.drop_column('coin_transactions', 'expired_at')
    op.drop_column('coin_transactions', 'expired')
    op.drop_column('coin_transactions', 'expires_at')
    # ### end Alembic commands ###