"""Make chat_hook session_id nullable

Revision ID: 5c9d8c63b1e0
Revises: add_chat_hooks_table
Create Date: 2025-07-18 22:18:01.451398

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5c9d8c63b1e0'
down_revision = 'add_chat_hooks_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_hooks', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_hooks', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###