"""add_fork_tracking_fields

Revision ID: 650245236082
Revises: 19e419a3a5ee
Create Date: 2025-11-04 07:26:35.396349

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '650245236082'
down_revision = '19e419a3a5ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_repositories', sa.Column('parent_repo_id', sa.BigInteger(), nullable=True))
    op.add_column('github_repositories', sa.Column('parent_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('github_repositories', sa.Column('can_push', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('github_repositories', sa.Column('can_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_github_repositories_parent_repo_id'), 'github_repositories', ['parent_repo_id'], unique=False)
    op.add_column('projects', sa.Column('is_fork_project', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('projects', sa.Column('original_issue_repo_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_projects_original_issue_repo_id'), 'projects', ['original_issue_repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_original_issue_repo_id'), table_name='projects')
    op.drop_column('projects', 'original_issue_repo_id')
    op.drop_column('projects', 'is_fork_project')
    op.drop_index(op.f('ix_github_repositories_parent_repo_id'), table_name='github_repositories')
    op.drop_column('github_repositories', 'can_admin')
    op.drop_column('github_repositories', 'can_push')
    op.drop_column('github_repositories', 'parent_full_name')
    op.drop_column('github_repositories', 'parent_repo_id')
    # ### end Alembic commands ###