"""Add approval_requests table for MCP approvals

Revision ID: 8002f2c420d0
Revises: 5c9d8c63b1e0
Create Date: 2025-07-18 22:52:03.521594

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8002f2c420d0'
down_revision = '5c9d8c63b1e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('display_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callback_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'timeout', name='mcpapprovalstatus'), nullable=True),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_project_id'], ['sub_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_request_id'), 'approval_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_approval_requests_session_id'), 'approval_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_sub_project_id'), 'approval_requests', ['sub_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_sub_project_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_session_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_request_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###