"""add test cases table

Revision ID: 4e5f9d2a8b3c
Revises: f2c291de5c2c
Create Date: 2025-08-13 03:43:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e5f9d2a8b3c'
down_revision = 'f2c291de5c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('test_steps', sa.String(), nullable=False),
    sa.Column('expected_result', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'passed', 'failed', name='testcasestatus'), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('execution_result', sa.String(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.execute("DROP TYPE testcasestatus")
    # ### end Alembic commands ###