"""Add test case hooks table

Revision ID: add_test_case_hooks_table
Revises: add_test_cases_table
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = 'add_test_case_hooks_table'
down_revision = '4e5f9d2a8b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case_hooks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('test_case_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('hook_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_hooks_conversation_id'), 'test_case_hooks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_test_case_hooks_session_id'), 'test_case_hooks', ['session_id'], unique=False)
    op.create_index(op.f('ix_test_case_hooks_test_case_id'), 'test_case_hooks', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_hooks_test_case_id'), table_name='test_case_hooks')
    op.drop_index(op.f('ix_test_case_hooks_session_id'), table_name='test_case_hooks')
    op.drop_index(op.f('ix_test_case_hooks_conversation_id'), table_name='test_case_hooks')
    op.drop_table('test_case_hooks')
    # ### end Alembic commands ###