"""Add IssueResolution table for GitHub issue resolution workflow

Revision ID: b8f90f39d891
Revises: cee25c3f611f
Create Date: 2025-11-03 10:00:55.023880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8f90f39d891'
down_revision = 'cee25c3f611f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first before dropping parent tables
    # Drop tables that depend on users_basic_auth_backup
    op.drop_table('user_tokens_backup')
    op.drop_table('audit_logs_backup')

    # Drop execution_logs before planning_sessions (FK dependency)
    op.drop_index('ix_execution_logs_task_id', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_planning_sessions_task_id', table_name='planning_sessions')
    op.drop_table('planning_sessions')

    # Now safe to drop users_basic_auth_backup
    op.drop_index('ix_users_email', table_name='users_basic_auth_backup')
    op.drop_index('ix_users_username', table_name='users_basic_auth_backup')
    op.drop_table('users_basic_auth_backup')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_context_questions_task_id', table_name='context_questions')
    op.drop_table('context_questions')
    op.drop_index('ix_issue_test_cases_resolution_id', table_name='issue_test_cases')
    op.drop_table('issue_test_cases')
    op.drop_column('approval_requests', 'updated_at')
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('chat_hooks', 'updated_at')
    op.drop_index('ix_chats_continuation_status', table_name='chats')
    op.drop_index('ix_chats_parent_message_id', table_name='chats')
    op.drop_constraint('fk_chats_parent_message_id', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'chats', ['parent_message_id'], ['id'])
    op.add_column('github_issues', sa.Column('repository_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('github_issues', sa.Column('author_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('github_issues', sa.Column('author_avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('github_issues', sa.Column('comments_count', sa.Integer(), nullable=False))
    op.add_column('github_issues', sa.Column('reactions_count', sa.Integer(), nullable=False))
    op.add_column('github_issues', sa.Column('github_closed_at', sa.DateTime(), nullable=True))
    op.add_column('github_issues', sa.Column('is_task_generated', sa.Boolean(), nullable=False))
    op.add_column('github_issues', sa.Column('generated_task_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('github_issues', sa.Column('last_synced_at', sa.DateTime(), nullable=False))
    op.add_column('github_issues', sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('github_issues', 'github_issue_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('github_issues', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('github_issues', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('github_issues', 'labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('github_issues', 'assignees',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('github_issues', 'html_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('github_issues', 'github_created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('github_issues', 'github_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('github_issues_github_issue_id_key', 'github_issues', type_='unique')
    op.drop_index('ix_github_issues_project_id', table_name='github_issues')
    op.create_index(op.f('ix_github_issues_github_issue_id'), 'github_issues', ['github_issue_id'], unique=False)
    op.create_index(op.f('ix_github_issues_repository_id'), 'github_issues', ['repository_id'], unique=False)
    op.create_index(op.f('ix_github_issues_state'), 'github_issues', ['state'], unique=False)
    op.drop_constraint('github_issues_resolution_task_id_fkey', 'github_issues', type_='foreignkey')
    op.drop_constraint('github_issues_project_id_fkey', 'github_issues', type_='foreignkey')
    op.create_foreign_key(None, 'github_issues', 'github_repositories', ['repository_id'], ['id'])
    op.create_foreign_key(None, 'github_issues', 'tasks', ['generated_task_id'], ['id'])
    op.drop_column('github_issues', 'resolution_task_id')
    op.drop_column('github_issues', 'pull_request_url')
    op.drop_column('github_issues', 'repository_url')
    op.drop_column('github_issues', 'milestone')
    op.drop_column('github_issues', 'pull_request_number')
    op.drop_column('github_issues', 'resolution_started_at')
    op.drop_column('github_issues', 'project_id')
    op.drop_column('github_issues', 'created_by')
    op.drop_column('github_issues', 'resolution_project_id')
    op.drop_column('github_issues', 'resolution_status')
    op.drop_column('github_issues', 'resolution_completed_at')
    op.add_column('issue_resolutions', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('github_issue_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('issue_number', sa.Integer(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('issue_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('issue_body', sa.Text(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('issue_labels', sa.JSON(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('resolution_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('resolution_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('pr_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('auto_query_triggered', sa.Boolean(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('auto_query_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('auto_query_completed', sa.Boolean(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('solution_approach', sa.Text(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('files_changed', sa.JSON(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('test_cases_generated', sa.Integer(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('test_cases_passed', sa.Integer(), nullable=False))
    op.add_column('issue_resolutions', sa.Column('analyzing_started_at', sa.DateTime(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('implementing_started_at', sa.DateTime(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('testing_started_at', sa.DateTime(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('pr_created_at', sa.DateTime(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('issue_resolutions', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.alter_column('issue_resolutions', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('issue_resolutions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_issue_resolutions_issue_id', table_name='issue_resolutions')
    op.create_index(op.f('ix_issue_resolutions_auto_query_session_id'), 'issue_resolutions', ['auto_query_session_id'], unique=False)
    op.create_index(op.f('ix_issue_resolutions_github_issue_id'), 'issue_resolutions', ['github_issue_id'], unique=False)
    op.create_index(op.f('ix_issue_resolutions_issue_number'), 'issue_resolutions', ['issue_number'], unique=False)
    op.create_index(op.f('ix_issue_resolutions_pr_number'), 'issue_resolutions', ['pr_number'], unique=False)
    op.create_index(op.f('ix_issue_resolutions_project_id'), 'issue_resolutions', ['project_id'], unique=False)
    op.create_index(op.f('ix_issue_resolutions_resolution_state'), 'issue_resolutions', ['resolution_state'], unique=False)
    op.create_index(op.f('ix_issue_resolutions_task_id'), 'issue_resolutions', ['task_id'], unique=True)
    op.drop_constraint('issue_resolutions_issue_id_fkey', 'issue_resolutions', type_='foreignkey')
    op.create_foreign_key(None, 'issue_resolutions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'issue_resolutions', 'github_issues', ['github_issue_id'], ['id'])
    op.drop_column('issue_resolutions', 'coding_standards')
    op.drop_column('issue_resolutions', 'status')
    op.drop_column('issue_resolutions', 'failed_tests')
    op.drop_column('issue_resolutions', 'progress_percentage')
    op.drop_column('issue_resolutions', 'external_task_id')
    op.drop_column('issue_resolutions', 'webhook_logs')
    op.drop_column('issue_resolutions', 'total_tests')
    op.drop_column('issue_resolutions', 'passed_tests')
    op.drop_column('issue_resolutions', 'external_project_id')
    op.drop_column('issue_resolutions', 'issue_id')
    op.drop_column('issue_resolutions', 'error_logs')
    op.drop_column('issue_resolutions', 'resolution_prompt')
    op.drop_column('issue_resolutions', 'current_phase')
    op.drop_column('issue_resolutions', 'repository_context')
    op.drop_index('ix_projects_github_repository_id', table_name='projects')
    op.alter_column('tasks', 'deployment_guide',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tasks', 'initial_description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('tasks', 'refined_requirements',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('test_case_hooks', 'updated_at')
    op.alter_column('test_cases', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('test_cases', 'test_code')
    op.drop_column('test_cases', 'error_message')
    op.drop_column('test_cases', 'execution_time_ms')
    op.drop_column('test_cases', 'test_type')
    op.drop_column('test_cases', 'name')
    op.drop_column('test_cases', 'actual_result')
    op.drop_column('test_cases', 'executed_at')
    op.alter_column('user_tokens', 'access_token_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('user_tokens', 'refresh_token_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('user_tokens', 'scope',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint('uq_users_github_id', 'users', type_='unique')
    op.drop_constraint('uq_users_github_login', 'users', type_='unique')
    op.drop_index('ix_users_github_id', table_name='users')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.drop_index('ix_users_github_login', table_name='users')
    op.create_index(op.f('ix_users_github_login'), 'users', ['github_login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_login'), table_name='users')
    op.create_index('ix_users_github_login', 'users', ['github_login'], unique=False)
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_index('ix_users_github_id', 'users', ['github_id'], unique=False)
    op.create_unique_constraint('uq_users_github_login', 'users', ['github_login'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('uq_users_github_id', 'users', ['github_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'bio',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_tokens', 'scope',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_tokens', 'refresh_token_encrypted',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_tokens', 'access_token_encrypted',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('test_cases', sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('test_cases', sa.Column('actual_result', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('test_cases', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('test_cases', sa.Column('test_type', sa.VARCHAR(length=50), server_default=sa.text("'unit'::character varying"), autoincrement=False, nullable=True))
    op.add_column('test_cases', sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_cases', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('test_cases', sa.Column('test_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('test_cases', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('test_case_hooks', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.alter_column('tasks', 'refined_requirements',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'initial_description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'deployment_guide',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_projects_github_repository_id', 'projects', ['github_repository_id'], unique=False)
    op.add_column('issue_resolutions', sa.Column('repository_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('current_phase', postgresql.ENUM('ANALYZING', 'IMPLEMENTING', 'TESTING', 'REVIEWING', name='resolutionphase'), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('resolution_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('error_logs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('issue_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('issue_resolutions', sa.Column('external_project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('passed_tests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('issue_resolutions', sa.Column('total_tests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('issue_resolutions', sa.Column('webhook_logs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('external_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('issue_resolutions', sa.Column('failed_tests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('issue_resolutions', sa.Column('status', postgresql.ENUM('PENDING', 'INITIALIZING', 'CODING', 'TESTING', 'PR_READY', 'COMPLETED', 'FAILED', name='resolutionstatus'), autoincrement=False, nullable=True))
    op.add_column('issue_resolutions', sa.Column('coding_standards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issue_resolutions', type_='foreignkey')
    op.drop_constraint(None, 'issue_resolutions', type_='foreignkey')
    op.create_foreign_key('issue_resolutions_issue_id_fkey', 'issue_resolutions', 'github_issues', ['issue_id'], ['id'])
    op.drop_index(op.f('ix_issue_resolutions_task_id'), table_name='issue_resolutions')
    op.drop_index(op.f('ix_issue_resolutions_resolution_state'), table_name='issue_resolutions')
    op.drop_index(op.f('ix_issue_resolutions_project_id'), table_name='issue_resolutions')
    op.drop_index(op.f('ix_issue_resolutions_pr_number'), table_name='issue_resolutions')
    op.drop_index(op.f('ix_issue_resolutions_issue_number'), table_name='issue_resolutions')
    op.drop_index(op.f('ix_issue_resolutions_github_issue_id'), table_name='issue_resolutions')
    op.drop_index(op.f('ix_issue_resolutions_auto_query_session_id'), table_name='issue_resolutions')
    op.create_index('ix_issue_resolutions_issue_id', 'issue_resolutions', ['issue_id'], unique=False)
    op.alter_column('issue_resolutions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('issue_resolutions', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('issue_resolutions', 'retry_count')
    op.drop_column('issue_resolutions', 'error_message')
    op.drop_column('issue_resolutions', 'pr_created_at')
    op.drop_column('issue_resolutions', 'testing_started_at')
    op.drop_column('issue_resolutions', 'implementing_started_at')
    op.drop_column('issue_resolutions', 'analyzing_started_at')
    op.drop_column('issue_resolutions', 'test_cases_passed')
    op.drop_column('issue_resolutions', 'test_cases_generated')
    op.drop_column('issue_resolutions', 'files_changed')
    op.drop_column('issue_resolutions', 'solution_approach')
    op.drop_column('issue_resolutions', 'auto_query_completed')
    op.drop_column('issue_resolutions', 'auto_query_session_id')
    op.drop_column('issue_resolutions', 'auto_query_triggered')
    op.drop_column('issue_resolutions', 'pr_state')
    op.drop_column('issue_resolutions', 'pr_url')
    op.drop_column('issue_resolutions', 'pr_number')
    op.drop_column('issue_resolutions', 'resolution_branch')
    op.drop_column('issue_resolutions', 'resolution_state')
    op.drop_column('issue_resolutions', 'issue_labels')
    op.drop_column('issue_resolutions', 'issue_body')
    op.drop_column('issue_resolutions', 'issue_title')
    op.drop_column('issue_resolutions', 'issue_number')
    op.drop_column('issue_resolutions', 'github_issue_id')
    op.drop_column('issue_resolutions', 'project_id')
    op.add_column('github_issues', sa.Column('resolution_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('resolution_status', postgresql.ENUM('PENDING', 'INITIALIZING', 'CODING', 'TESTING', 'PR_READY', 'COMPLETED', 'FAILED', name='resolutionstatus'), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('resolution_project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('github_issues', sa.Column('resolution_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('pull_request_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('milestone', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('repository_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('pull_request_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('github_issues', sa.Column('resolution_task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'github_issues', type_='foreignkey')
    op.drop_constraint(None, 'github_issues', type_='foreignkey')
    op.create_foreign_key('github_issues_project_id_fkey', 'github_issues', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('github_issues_resolution_task_id_fkey', 'github_issues', 'tasks', ['resolution_task_id'], ['id'])
    op.drop_index(op.f('ix_github_issues_state'), table_name='github_issues')
    op.drop_index(op.f('ix_github_issues_repository_id'), table_name='github_issues')
    op.drop_index(op.f('ix_github_issues_github_issue_id'), table_name='github_issues')
    op.create_index('ix_github_issues_project_id', 'github_issues', ['project_id'], unique=False)
    op.create_unique_constraint('github_issues_github_issue_id_key', 'github_issues', ['github_issue_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('github_issues', 'github_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('github_issues', 'github_created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('github_issues', 'html_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('github_issues', 'assignees',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('github_issues', 'labels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('github_issues', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('github_issues', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('github_issues', 'github_issue_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('github_issues', 'priority')
    op.drop_column('github_issues', 'last_synced_at')
    op.drop_column('github_issues', 'generated_task_id')
    op.drop_column('github_issues', 'is_task_generated')
    op.drop_column('github_issues', 'github_closed_at')
    op.drop_column('github_issues', 'reactions_count')
    op.drop_column('github_issues', 'comments_count')
    op.drop_column('github_issues', 'author_avatar_url')
    op.drop_column('github_issues', 'author_login')
    op.drop_column('github_issues', 'repository_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('fk_chats_parent_message_id', 'chats', 'chats', ['parent_message_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_chats_parent_message_id', 'chats', ['parent_message_id'], unique=False)
    op.create_index('ix_chats_continuation_status', 'chats', ['continuation_status'], unique=False)
    op.add_column('chat_hooks', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.alter_column('audit_logs', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('approval_requests', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('planning_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('step_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('step_type', postgresql.ENUM('FILE_CREATE', 'FILE_EDIT', 'FILE_DELETE', 'DIRECTORY_CREATE', 'COMMAND_EXECUTE', 'API_CALL', 'TEST_RUN', 'DEPENDENCY_INSTALL', 'GIT_OPERATION', 'VALIDATION', 'AI_QUERY', 'USER_INPUT', name='executionsteptype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'RETRY', 'BLOCKED', name='executionstatus'), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('files_affected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('lines_added', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lines_removed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('command', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('command_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_recovery', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validation_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('depends_on_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blocking_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_assisted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requires_approval', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('approval_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planning_session_id'], ['planning_sessions.id'], name='execution_logs_planning_session_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='execution_logs_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='execution_logs_pkey')
    )
    op.create_index('ix_execution_logs_task_id', 'execution_logs', ['task_id'], unique=False)
    op.create_table('audit_logs_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_basic_auth_backup.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_table('issue_test_cases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resolution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('test_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test_type', postgresql.ENUM('UNIT', 'INTEGRATION', 'E2E', name='testtype'), autoincrement=False, nullable=False),
    sa.Column('test_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('test_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'FIXED', name='teststatus'), autoincrement=False, nullable=False),
    sa.Column('execution_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fix_attempted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fix_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fix_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fixed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['issue_resolutions.id'], name='issue_test_cases_resolution_id_fkey'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], name='issue_test_cases_test_case_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='issue_test_cases_pkey')
    )
    op.create_index('ix_issue_test_cases_resolution_id', 'issue_test_cases', ['resolution_id'], unique=False)
    op.create_table('user_tokens_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_token_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_basic_auth_backup.id'], name='user_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_tokens_pkey')
    )
    op.create_table('context_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_category', postgresql.ENUM('FUNCTIONAL', 'TECHNICAL', 'USER_EXPERIENCE', 'INTEGRATION', 'PERFORMANCE', 'SECURITY', 'TESTING', 'DEPLOYMENT', name='questioncategory'), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_type', postgresql.ENUM('TEXT', 'LONG_TEXT', 'CHOICE', 'MULTI_SELECT', 'CODE', 'FILE_UPLOAD', 'BOOLEAN', 'NUMBER', name='questiontype'), autoincrement=False, nullable=False),
    sa.Column('help_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('validation_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('depends_on_question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dependency_condition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('generation_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['depends_on_question_id'], ['context_questions.id'], name='context_questions_depends_on_question_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='context_questions_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='context_questions_pkey')
    )
    op.create_index('ix_context_questions_task_id', 'context_questions', ['task_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_read', 'notifications', ['read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_table('users_basic_auth_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users_basic_auth_backup', ['username'], unique=True)
    op.create_index('ix_users_email', 'users_basic_auth_backup', ['email'], unique=True)
    op.create_table('planning_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'REQUIRES_REVISION', name='planningstatus'), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planning_prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('implementation_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('architecture_decisions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estimated_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complexity_level', postgresql.ENUM('TRIVIAL', 'SIMPLE', 'MODERATE', 'COMPLEX', 'VERY_COMPLEX', name='complexitylevel'), autoincrement=False, nullable=True),
    sa.Column('complexity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('external_dependencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('system_requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('test_strategy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('planning_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('planning_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='planning_sessions_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planning_sessions_pkey')
    )
    op.create_index('ix_planning_sessions_task_id', 'planning_sessions', ['task_id'], unique=False)
    # ### end Alembic commands ###