"""add_mcp_servers_to_task

Revision ID: f2c291de5c2c
Revises: add_new_webhook_fields
Create Date: 2025-07-19 15:01:23.819543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f2c291de5c2c'
down_revision = 'add_new_webhook_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('mcp_servers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'mcp_servers')
    # ### end Alembic commands ###